

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      RABBITMQ_URI: amqp://admin:123456@rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: 123456
    ports:
      - "3000:3000"
    env_file: ./auth/.env
    depends_on:
      - mongo

  product:
    build: 
      context: ./product
      dockerfile: Dockerfile
    container_name: product
    environment:
      RABBITMQ_URI: amqp://admin:123456@rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: 123456
    ports:
      - "3001:3001"
    env_file: ./product/.env
    depends_on:
      - mongo
      - rabbitmq

  order:
    build: 
      context: ./order
      dockerfile: Dockerfile
    container_name: order
    environment:
      RABBITMQ_URI: amqp://admin:123456@rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: 123456
    ports:
      - "3002:3002"
    env_file: ./order/.env
    depends_on:
      - mongo
      - rabbitmq

  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      RABBITMQ_URI: amqp://admin:123456@rabbitmq:5672
      RABBITMQ_USER: admin
      RABBITMQ_PASS: 123456
    ports:
      - "3003:3003"
    depends_on:
      - auth
      - product
      - order

volumes:
  mongo-data:
